<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" xmlns:moz="http://www.mozilla.org/2006/browser/search/">
    <ShortName>eZ Documentation</ShortName>
    <Description>Atlassian Confluence Search Provider</Description>
    <Image height="16" width="16" type="image/x-icon">https://doc.ez.no/images/logo/confluence_48_white.png</Image>
    <Image height="64" width="64" type="image/png">https://doc.ez.no/images/logo/confluence_128_white.png</Image>
    <Url type="text/html" template="https://doc.ez.no/dosearchsite.action?queryString={searchTerms}"/>
    <Query role="example" searchTerms="Confluence"/>
    <InputEncoding>UTF-8</InputEncoding>
    <moz:SearchForm>https://doc.ez.no/searchsite.action</moz:SearchForm>
</OpenSearchDescription>